In [2]:
import numpy as np

In [6]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,11,5)

array([ 0,  5, 10])

In [3]:
biasa = np.arange(1,10)
dgninter = np.arange(0,11,5)
print(biasa)
print(dgninter)

[1 2 3 4 5 6 7 8 9]
[ 0  5 10]


In [7]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros(3)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.random.rand(2)

array([0.22843004, 0.84311399])

In [12]:
np.random.rand(5,5)

array([[0.54080441, 0.35295167, 0.15356733, 0.47104891, 0.98065623],
       [0.11091989, 0.84848462, 0.42704661, 0.11633539, 0.05922056],
       [0.0274205 , 0.40382408, 0.55800016, 0.38407453, 0.31929   ],
       [0.94411052, 0.79627145, 0.38704637, 0.07467496, 0.7567503 ],
       [0.78480803, 0.38442181, 0.76291816, 0.78861181, 0.63292455]])

In [13]:
np.random.randint(1,100)

41

In [14]:
np.random.randint(1,100,10)

array([ 5, 50, 28, 63, 68,  4, 31, 45, 35, 18])

In [15]:
arr = np.arange(0,11)
arr[0:5]

array([0, 1, 2, 3, 4])

In [15]:
arr = np.arange(0,10)
# arr[0:5]
print(arr)
mat = arr.reshape(5,2)
print(mat)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

print(arr_2d) #menampilkan array
print(arr_2d[1]) #mengambil array index pertama
print(arr_2d[1][0]) #menggambil nilai index 0 didalam index 1
print(arr_2d[:2,1:])

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[20 25 30]
20
[[10 15]
 [25 30]]


In [19]:
import numpy as np
arr = np.arange(0,10)
plus = arr + arr
kali = arr * arr
kurang = arr - arr
print(plus)
print(kali)
print(kurang)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0 0 0 0 0 0 0 0 0 0]


In [18]:
a = np.sqrt(arr)
print(a)
print()
exp = np.exp(arr)
print(exp)
print()
max = np.max(arr) 
print(max)
print()
sin  = np.sin(arr)
print(sin)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]

9

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
